In [1]:
import numpy as np  
arr = np.array([[1,2,3],[3,6,8]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3]
 [3 6 8]]
<class 'numpy.ndarray'>
2


# find dimensions

In [2]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print("a:", a.ndim)
print("b:", b.ndim)
print("c:", c.ndim)
print("d:", d.ndim)


a: 0
b: 1
c: 2
d: 3


**how to set dimension of ndarray**

In [3]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


---

# array are indexed

In [4]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [5]:
a = np.array([[1, 2],
             [3, 4],
             [5, 6]], dtype='float64')
print(a)
print('number of dimensions:', a.ndim)
print('shape:', a.shape) 
print('size:', a.size) 
print('dtype:', a.dtype) 

[[1. 2.]
 [3. 4.]
 [5. 6.]]
number of dimensions: 2
shape: (3, 2)
size: 6
dtype: float64


In [6]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [7]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [8]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [9]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


In [10]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in arr:
  print(x)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [11]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [12]:
a = np.arange(8).reshape(2, 4)
print(a)

print("transpose \n",a.T)

[[0 1 2 3]
 [4 5 6 7]]
transpose 
 [[0 4]
 [1 5]
 [2 6]
 [3 7]]


**shows the index**

In [13]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [14]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])



arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [15]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
np.sum(arr, axis=1)


array([ 6, 15, 24])

In [16]:
arr1 = np.array([[1, 2, 3]])

arr2 = np.array([[4, 5, 6]])

arr3 = np.array([[7, 8, 9]])

arr = np.stack((arr1, arr2, arr3), axis=2)

print(arr)

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


In [17]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])

arr = np.hstack((arr1, arr2, arr3))

print(arr)

[1 2 3 4 5 6 7 8 9]


In [18]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])

arr = np.vstack((arr1, arr2, arr3))

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
a = np.arange(12).reshape(2, 6)
x, y, z = np.array_split(a, 3, axis=1)
print(x)
print(y)
print(z)

[[0 1]
 [6 7]]
[[2 3]
 [8 9]]
[[ 4  5]
 [10 11]]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [21]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [24]:
a = np.random.randint(0, 10, 4) # آرایه‌ای شامل 4 عضو تصادفی در بازه 0 تا 9 
b = np.random.randint(0, 10, 4) # آرایه‌ای شامل 4 عضو تصادفی در بازه 0 تا 9 
print('a =', a)
print('b =', b)

a = [9 6 3 8]
b = [8 6 3 2]


In [25]:
a = np.array([0, 1, 2, 3])
b = np.array([-2, 10, 1, 5])
print('a + b =', np.add(a, b)) 
print('a + b =', a + b) # است a + b معادل np.add(a, b)

a + b = [-2 11  3  8]
a + b = [-2 11  3  8]


In [26]:
print('a - b =', np.subtract(a, b)) 
print('a - b =', a - b) # است a - b معادل np.subtract(a, b)

a - b = [ 2 -9  1 -2]
a - b = [ 2 -9  1 -2]


In [27]:
print('a * b =', np.multiply(a, b)) 
print('a * b =', a * b) # است a * b معادل np.multiply(a, b)

a * b = [ 0 10  2 15]
a * b = [ 0 10  2 15]


In [28]:
print('a / b = ',np.divide(a, b))
print('a / b = ', a / b)

a / b =  [-0.   0.1  2.   0.6]
a / b =  [-0.   0.1  2.   0.6]


In [29]:
a = np.random.randint(0, 20, 5)
b = np.random.randint(-20, 0, 5)
print(f'a : {a}')
print(f'b : {b}')

a : [15  3  8 19  2]
b : [-14  -9 -15  -6  -9]


In [30]:
print('absolute values of b =', np.abs(b)) 

print('square values of a =', np.square(a)) 

absolute values of b = [14  9 15  6  9]
square values of a = [225   9  64 361   4]


In [31]:
arr = np.random.randint(0, 2000, 10)
print(arr)
print('Max: ', np.max(arr))
print('Min: ', np.min(arr))
print('Sum: ', np.sum(arr))

[ 140  134 1402 1672   54  848 1921  734  994 1815]
Max:  1921
Min:  54
Sum:  9714


In [32]:
big_array = np.random.rand(1000*1000)
%timeit sum(big_array)
%timeit np.sum(big_array)

59.2 ms ± 11.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
425 μs ± 80.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [33]:
a = np.random.randint(0, 10, (3, 4))
print(a)



[[6 7 6 0]
 [0 5 2 6]
 [9 5 6 2]]


In [34]:
a.max(axis=1)

array([7, 6, 9], dtype=int32)

In [35]:
a.max(axis=0)

array([9, 7, 6, 6], dtype=int32)

In [36]:
heights = np.array([[194, 185, 183, 184, 178, 178, 190, 187, 187, 179, 186], 
                    [192, 173, 194, 184, 170, 189, 170, 170, 176, 173, 185]])
print('Iran vs Spain')
print('Mean height:', heights.mean(axis=1))
print('Standard deviation:', heights.std(axis=1))

Iran vs Spain
Mean height: [184.63636364 179.63636364]
Standard deviation: [4.79152144 8.91650897]


In [37]:
print('Min:', np.min(heights, axis=1)) 
print('25th percentile:', np.percentile(heights, 25, axis=1)) 
print('Median:', np.median(heights, axis=1))
print('75th percentile:', np.percentile(heights, 75, axis=1))
print('Max:', np.max(heights, axis=1))

Min: [178 170]
25th percentile: [181.  171.5]
Median: [185. 176.]
75th percentile: [187. 187.]
Max: [194 194]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [39]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [40]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


#index of a max num or min num

In [41]:
a = np.random.randint(0, 10, (3, 4))
print(a)
print("\nIndex of Max element : ", np.argmax(a, axis=0)) 
print("\nIndex of Max element : ", np.argmax(a, axis=1)) 

[[8 5 8 0]
 [3 2 9 2]
 [0 6 8 2]]

Index of Max element :  [0 2 1 1]

Index of Max element :  [0 2 2]


In [42]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 2, 2, 2])
a * b

array([0, 2, 4, 6])

In [43]:
arr = np.random.randint(5, 25,(4, 7))
print(arr)

[[ 6 12 11 19  8 12 24]
 [19 19 11 18  5  6  5]
 [ 7 21 23 13 13 24  8]
 [13 18 13  6 21 17 18]]


In [44]:
arr > 20

array([[False, False, False, False, False, False,  True],
       [False, False, False, False, False, False, False],
       [False,  True,  True, False, False,  True, False],
       [False, False, False, False,  True, False, False]])

In [45]:
np.max(arr, axis=0)

array([19, 21, 23, 19, 21, 24, 24], dtype=int32)

In [46]:
np.sum(arr ,axis=0)

array([45, 70, 58, 56, 47, 59, 55])

In [47]:
np.any(arr < 5)

np.False_

In [48]:
np.sum((arr > 10) & (arr < 20))

np.int64(15)

In [49]:
print(arr[arr > 15].mean())

20.083333333333332


In [2]:
import numpy as np
arr = np.random.randint(0, 24, (4, 2,3))
print(arr)
np.sum(arr, axis=0)

[[[14 22  2]
  [ 6  1 12]]

 [[12 21 16]
  [ 3  2  9]]

 [[ 8 12  1]
  [18  2  4]]

 [[10 17  1]
  [14 15 22]]]


array([[44, 72, 20],
       [41, 20, 47]])

In [51]:
np.min(arr, axis=0)

array([15, 10,  4,  0,  2,  3], dtype=int32)

In [52]:
np.max(arr, axis=0)

array([23, 21, 19, 19, 11, 17], dtype=int32)

In [53]:
print(arr > 10)

[[ True  True  True  True False False]
 [ True False False False False False]
 [ True  True  True False  True  True]
 [ True  True False  True False  True]]


In [66]:
a = np.array([[2, 3, 4],[6, 0 , 0], [0, 0, 1]])
print(a)

[[2 3 4]
 [6 0 0]
 [0 0 1]]


In [85]:
a.reshape(3,-1,3)
print(a)

[[2 3 4]
 [6 0 0]
 [0 0 1]]


In [73]:
np.nonzero(a)

(array([0, 0, 0, 1, 2]), array([0, 1, 2, 0, 2]))

In [57]:
arr = np.random.randint(0, 100, (2,5,4))
print(arr)
for x in arr.flat:
    print(x)

[[[ 8 33 22 92]
  [41 27 87 24]
  [94 47 21 46]
  [19 21 74 73]
  [14 45 70  2]]

 [[52  6 35 18]
  [46 40 47 10]
  [21 70 66 77]
  [64 23 52 92]
  [ 6  2 49 63]]]
8
33
22
92
41
27
87
24
94
47
21
46
19
21
74
73
14
45
70
2
52
6
35
18
46
40
47
10
21
70
66
77
64
23
52
92
6
2
49
63


In [58]:
a = np.arange(12)**2  # the first 12 square numbers
i = np.array([1, 1, 3, 8, 5])  # an array of indices
print("a[i]:\n ", a[i])  # the elements of `a` at the positions `i`
j = np.array([[3, 4], [9, 7]])  # a bidimensional array of indices
print("a[j]: \n", a[j])  # the same shape as `j`

a[i]:
  [ 1  1  9 64 25]
a[j]: 
 [[ 9 16]
 [81 49]]


In [59]:
time = np.linspace(20, 145, 5)  # time scale
data = np.sin(np.arange(20)).reshape(5, 4)  # 4 time-dependent series
print(time)
print(data)
# index of the maxima for each series
ind = data.argmax(axis=0)
print(ind)
# times corresponding to the maxima
time_max = time[ind]
data_max = data[ind, range(data.shape[1])]  # => data[ind[0], 0], data[ind[1], 1]...
print(time_max)
print(data_max)
np.all(data_max == data.max(axis=0))

[ 20.    51.25  82.5  113.75 145.  ]
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[ 82.5   20.   113.75  51.25]
[0.98935825 0.84147098 0.99060736 0.6569866 ]


np.True_

In [60]:
arr = np.random.randint(0, 10, (4, 5))
print(arr)


[[9 1 1 9 7]
 [4 0 7 6 6]
 [3 0 8 3 6]
 [9 8 2 0 4]]



# Starting new tests


In [4]:
import numpy as np
arr = np.random.randint(0, 10, (4, 5))
print(arr)

[[8 0 9 8 6]
 [5 2 3 5 4]
 [4 6 6 2 5]
 [1 1 7 9 5]]


In [6]:
arr2 = np.random.randint(0, 10, (4, 5))
print(arr2)

[[0 5 1 8 2]
 [4 4 5 2 6]
 [0 6 4 1 7]
 [3 7 5 1 7]]


In [13]:
print(arr * arr2)
%timeit arr* arr2

[[ 0  0  9 64 12]
 [20  8 15 10 24]
 [ 0 36 24  2 35]
 [ 3  7 35  9 35]]
364 ns ± 48.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
mul = np.multiply(arr, arr2)
print(mul)
%timeit np.multiply(arr, arr2)

[[ 0  0  9 64 12]
 [20  8 15 10 24]
 [ 0 36 24  2 35]
 [ 3  7 35  9 35]]
432 ns ± 151 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
