# **NumPy?**

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

---

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

---

# **Why is NumPy Faster Than Lists?**
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

---

# __Installation of NumPy__
% pip install numpy

or

C:\Users\Your Name>pip install numpy   in terminal

---

1.  Array Definition
2.  Working with Array
3.  General Functions
4.  Aggregate Functions
5.  Comparison and Boolean logic
6.  Indexing with arrays
7.  Sorting and Linear Algebra

----

----

## How to import and check our numpy version??

In [1]:
import numpy as np # عموما به طور قراردادی از کتابخانهٔ نامپای به این شکل استفاده می‌شود
np.__version__ 

'2.1.2'

# In this Part We talk mostly about
-  ## Array definition and its methods and how they work and why we need array

__0-D Arrays__

In [2]:
arr = np.array(42)

print(arr)

42


---

__1-D Arrays__

In [3]:
np.array([1, 2, 3]) # آرایه‌ی یک بعدی شامل 3 عدد

array([1, 2, 3])

---

**2-D Arrays**

In [4]:
np.array([[1, 2], # آرایه‌ی دو بعدی 2*3 شامل 6 عدد 
         [3, 4],
         [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

---

**3-D arrays**

In [5]:
np.array([[['000', '001'], ['010', '011']], # آرایه‌ی سه بعدی 2*2*2 شامل 8 رشته
          [['100', '101'], ['110', '111']]])
# نوع خانه‌های آرایه‌ی را نشان می‌دهد و dtype
# که نوع این آرایه‌ی می‌شود به معنای رشته یونی‌کد 3 حرفی است <U3

array([[['000', '001'],
        ['010', '011']],

       [['100', '101'],
        ['110', '111']]], dtype='<U3')

![](https://quera.org/qbox/view/s1CbjTbEPH/dimensions.PNG)

---

# Check Number of Dimensions?
**NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.**

In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


---

# Higher Dimensional Arrays
*An array can have any number of dimensions.*

**When the array is created, you can define the number of dimensions by using the ndmin argument.**

In [7]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


---

# Data Types in NumPy
*NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.*

**Below is a list of all data types in NumPy and the characters used to represent them.**

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [8]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [9]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


**Creating Arrays With a Defined Data Type**

In [10]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [11]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [12]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [133]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


---

In [41]:
np.zeros(3) # آرایه‌ی یک بعدی شامل 3 عدد حقیقی برابر صفر

array([0., 0., 0.])

---

In [42]:
np.ones((2, 3)) # آرایه‌‌ی دو بعدی 3*2 شامل 6 عدد حقیقی برابر یک

array([[1., 1., 1.],
       [1., 1., 1.]])

---

In [43]:
np.full((3, 2), '#') # آرایه‌ی دو بعدی 2*3 شامل 6 رشتهٔ '#' یکسان

array([['#', '#'],
       ['#', '#'],
       ['#', '#']], dtype='<U1')

---

In [44]:
np.arange(0, 15, 4) # آرایه‌ی یک بعدی شامل اعداد صحیح پیش از 15 با شروع از 0 و با فاصله 4

array([ 0,  4,  8, 12])

---

In [45]:
np.linspace(0, 20, 5) # آرایه‌ی یک بعدی شامل 5 عدد حقیقی در بازه 0 تا 20 (شامل این دو) با فاصله برابر

array([ 0.,  5., 10., 15., 20.])

---

In [46]:
np.eye(3) # آرایه‌ی دو بعدی 3*3 متناظر با ماتریس همانی (قطر 1 و باقی خانه‌ها 0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---

In [47]:
np.empty(3) # آرایه‌ی یک بعدی شامل 3 عدد نامشخص (بسته به مقدار داخل حافظه)

array([1., 1., 1.])

---

In [48]:
np.random.random(3) # آرایه‌ی یک بعدی شامل 3 عدد تصادفی از توزیع یکنواخت بین 0 و 1

array([0.66430426, 0.75378424, 0.49093622])

---

In [49]:
np.random.randint(0, 10, (3, 3)) # آرایه‌ی دو بعدی 3*3 شامل اعداد صحیح تصادفی بین 0 تا 9 

array([[2, 2, 8],
       [5, 6, 3],
       [1, 3, 4]])

---

In [50]:
np.random.normal(0, 1, (2, 3)) # آرایه‌ی دو بعدی 3*2 شامل اعداد تصادفی از توزیع نرمال با میانگین 0 و واریانس 1 

array([[-2.46415948,  0.02305033,  0.72867372],
       [-1.02779816,  0.68875081, -1.127136  ]])

---

In [51]:
a = np.random.randint(0, 10, (2, 3))
np.full_like(a, 3) # آرایه‌ی پر از 3 با ابعاد مشابه آرایه ورودی (3*2)

array([[3, 3, 3],
       [3, 3, 3]])

---

![](https://quera.org/qbox/view/un7crtXtLU/full_like.gif)

---

In [52]:
np.array([False, True], dtype='bool_') # نوع مقدار بولی
# کاراکتر _ برای اشاره به نوع داخل نامپای است اما می‌توان آن را برداشت

array([False,  True])

---

In [53]:
np.array([1, 2, 3.14], dtype='int_') # نوع عدد صحیح (عدد سوم تبدیل به 3 می‌شود)

array([1, 2, 3])

---

In [54]:
np.array([2.71828182845, 3.14159265359], dtype='float64') # نوع عدد حقیقی 64 بیتی

array([2.71828183, 3.14159265])

---

In [55]:
np.array([255], dtype='uint8') # نوع عدد صحیح نامنفی 8 بیتی

array([255], dtype=uint8)

---

In [56]:
np.array(['Hello', 'World'], dtype='str_') # نوع رشته

array(['Hello', 'World'], dtype='<U5')

---

In [57]:
a = np.array([[1, 2],
             [3, 4],
             [5, 6]], dtype='float64')
print(a)
print('number of dimensions:', a.ndim) # تعداد ابعاد آرایه
print('shape:', a.shape) # اندازه ابعاد آرایه
print('size:', a.size) # تعداد خانه‌های آرایه
print('dtype:', a.dtype) # نوع داده آرایه

[[1. 2.]
 [3. 4.]
 [5. 6.]]
number of dimensions: 2
shape: (3, 2)
size: 6
dtype: float64


---

---

In [58]:
c = np.array(['h', 'e', 'l', 'l', 'o'])
print(c)
print(c.itemsize, 'bytes') # تعداد بایت برای هر خانه آرایه
print(c.nbytes, 'bytes') # تعداد بایت برای کل آرایه

['h' 'e' 'l' 'l' 'o']
4 bytes
20 bytes


---

# NumPy Array Iterating

In [ ]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [138]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [139]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [140]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [141]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


---

# **Now it's time to learn Indexing**

In [59]:
a = np.array([5, 1, 8, 4])
print(a)

[5 1 8 4]


In [60]:
print('a[0] =', a[0])
print('a[2] =', a[2])
print('a[-1] =', a[-1])

a[0] = 5
a[2] = 8
a[-1] = 4


---

In [13]:
a = np.random.randint(0, 10, (3, 5))
print(a)

[[8 6 8 8 9]
 [4 3 3 7 2]
 [0 3 3 7 0]]


In [14]:
print('a[2, 3] =', a[2, 3])

a[2, 3] = 7


In [15]:
a[2, 3] = 10
print('a[2, 3] =', a[2, 3])

a[2, 3] = 10


In [16]:
print(a)

[[ 8  6  8  8  9]
 [ 4  3  3  7  2]
 [ 0  3  3 10  0]]


# Negative Indexing
*Use negative indexing to access an array from the end.*

In [126]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


---

# **Slicing??**

In [65]:
a = np.array([0, 1, 2, 3, 4])
print(a)

[0 1 2 3 4]


In [66]:
print(a[:3])
print(a[2:4])
print(a[1:5:2])
print(a[::-1])

[0 1 2]
[2 3]
[1 3]
[4 3 2 1 0]


# Negative Slicing
*Use the minus operator to refer to an index from the end:*

In [127]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


---

In [17]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8],
              [9, 10, 11]])
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [18]:
print(a[:2, 1:])

[[1 2]
 [4 5]]


In [69]:
print(a[1:3, ::2])

[[3 5]
 [6 8]]


In [70]:
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [71]:
print(a[:2, 1])

[1 4]


In [72]:
print(a[2, :])

[6 7 8]


In [73]:
print(a[:, 1])

[ 1  4  7 10]


In [74]:
print(a[2])

[6 7 8]


---

**view and not a copy**

In [20]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
sub_a = a[1:3, 1:]
print(sub_a)
sub_a[0, 0] = 10
print(a)

[[4 5]
 [7 8]]
[[ 0  1  2]
 [ 3 10  5]
 [ 6  7  8]]


---

**method for copying an array**

In [76]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
sub_copy_a = a[2:4, 1:].copy()
sub_copy_a[0, 0] = 10
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


---

# **Reshaping??**

In [77]:
a = np.arange(16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [78]:
print(a.reshape(4, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [79]:
a = np.array([1, 2, 3])
print(a.reshape(3, 1))

[[1]
 [2]
 [3]]


In [80]:
print(a.reshape(1, 3))

[[1 2 3]]


In [25]:
a = np.arange(12)
print(a.reshape(2, -1, 3))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


---

# **Flattening??**

In [82]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print(a.reshape(-1))

[0 1 2 3 4 5 6 7 8]


---

# **Transpose??**

In [83]:
a = np.arange(8).reshape(2, 4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [84]:
print(a.T)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


![](https://quera.org/qbox/view/xfWkJ9uk6z/transpose.gif)

In [85]:
a = np.arange(24).reshape(2, 3, 4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [86]:
np.transpose(a)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

---

In [87]:
a = np.arange(8).reshape(2, 4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [88]:
a.swapaxes(0, 1)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

![](https://quera.org/qbox/view/Lx2KUrWiwA/axis.png)

---

# **Concatenate??**

In [89]:
x = np.arange(6).reshape(2, 3)
y = np.arange(6, 12).reshape(2, 3)
z = np.arange(12, 15).reshape(1, 3)
print(x)

[[0 1 2]
 [3 4 5]]


In [90]:
print(y)

[[ 6  7  8]
 [ 9 10 11]]


In [91]:
print(z)

[[12 13 14]]


In [92]:
a = np.concatenate([x, y, z])
print(a,"\n","shape of a is = ",a.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 
 shape of a is =  (5, 3)


In [93]:
np.concatenate([x, y], axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

![](https://quera.org/qbox/view/Yw0nPkHTuR/concatenate.gif)

---

# Joining Arrays Using Stack Functions
*Stacking is same as concatenation, the only difference is that stacking is done along a new axis.*

In [144]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


**Stacking Along Rows**

In [145]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


**Stacking Along Columns**

In [146]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


**Stacking Along Height (depth)**

In [147]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


---

# **Split??**

In [94]:
a = np.arange(10)
x, y, z = np.split(a, [2, 5])
print(x)
print(y)
print(z)

[0 1]
[2 3 4]
[5 6 7 8 9]


In [95]:
a = np.arange(12).reshape(2, 6)
x, y, z = np.split(a, 3, axis=1)
print(x)
print(y)
print(z)

[[0 1]
 [6 7]]
[[2 3]
 [8 9]]
[[ 4  5]
 [10 11]]


![](https://quera.org/qbox/view/SHhG2Vh91J/split.png)

---

# **General Functions??**

In [96]:
a = np.random.randint(0, 10, 4) # آرایه‌ای شامل 4 عضو تصادفی در بازه 0 تا 9 
b = np.random.randint(0, 10, 4) # آرایه‌ای شامل 4 عضو تصادفی در بازه 0 تا 9 
print('a =', a)
print('b =', b)

a = [9 4 2 7]
b = [9 3 7 0]


In [97]:
def cal_sum(a, b) :
    output = np.empty(len(a), dtype='int_')
    for i in range(len(a)):
        output[i] = a[i] + b[i]
    return output

print(cal_sum(a, b))

[18  7  9  7]


In [98]:
big_size = 10*1000*1000
a = np.random.randint(0, 10, big_size) 
b = np.random.randint(0, 10, big_size) 
%timeit cal_sum(a, b)

3.53 s ± 106 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


---

In [99]:
%timeit np.add(a, b)

21 ms ± 747 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [100]:
a = np.random.randint(0, 10, 4) 
b = np.random.randint(0, 10, 4) 
print(np.add(a, b)) # قالب قبلی
print(a + b) # استفاده از عملگر معادل

[10 16 11 18]
[10 16 11 18]


In [101]:
a = np.array([0, 1, 2, 3])
b = np.array([-2, 10, 1, 5])
print('a + b =', np.add(a, b)) 
print('a + b =', a + b) # است a + b معادل np.add(a, b)

a + b = [-2 11  3  8]
a + b = [-2 11  3  8]


---

In [102]:
print('a - b =', np.subtract(a, b)) 
print('a - b =', a - b) # است a - b معادل np.subtract(a, b)

a - b = [ 2 -9  1 -2]
a - b = [ 2 -9  1 -2]


---

In [103]:
print('a * b =', np.multiply(a, b)) 
print('a * b =', a * b) # است a * b معادل np.multiply(a, b)

a * b = [ 0 10  2 15]
a * b = [ 0 10  2 15]


---

In [104]:
print('a / b =', np.divide(a, b)) 
print('a / b =', a / b) # است a / b معادل np.divide(a, b)

a / b = [-0.   0.1  2.   0.6]
a / b = [-0.   0.1  2.   0.6]


---

In [105]:
a = np.random.randint(0, 11, 5) # آرایه‌ای شامل 5 عدد تصادفی در بازه 0 تا 10
b = np.random.randint(-10, 11, 5) # آرایه‌ای شامل 5 عدد تصادفی در بازه 10- تا 10
print('a =', a)
print('b =', b)

a = [ 2  2  9  3 10]
b = [-8 -6  6 -3 -5]


---

In [106]:
print('absolute values of b =', np.abs(b)) 

absolute values of b = [8 6 6 3 5]


---

In [107]:
print('square values of a =', np.square(a)) 

square values of a = [  4   4  81   9 100]


---

In [108]:
np.seterr(invalid="ignore") # خطای ناشی از عملیات غیرمجاز را نادیده می‌گیرد
a = np.array([1 , 2 , -3 , 4, -5])
print('a = ', a)
print('isnan results for a =', np.isnan(a))
print('sqrt(a) = ', np.sqrt(a))
print('isnan resultes for sqrt(a) =', np.isnan(np.sqrt(a)))

a =  [ 1  2 -3  4 -5]
isnan results for a = [False False False False False]
sqrt(a) =  [1.         1.41421356        nan 2.                nan]
isnan resultes for sqrt(a) = [False False  True False  True]


---

In [109]:
a = np.random.randint(0, 10, 20)
print(a)
print('sum =', np.sum(a))
print('min =', np.min(a))
print('max =', np.max(a))

[7 4 8 7 2 1 8 1 2 1 1 0 0 9 4 4 6 2 8 1]
sum = 76
min = 0
max = 9


In [110]:
print(a.min(), a.max(), a.sum())

0 9 76


---

In [111]:
big_array = np.random.rand(1000*1000)
%timeit sum(big_array)
%timeit np.sum(big_array)

82 ms ± 2.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.24 ms ± 35.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [26]:
a = np.random.randint(0, 10, (3, 4))
print(a)

[[1 6 4 0]
 [4 4 7 5]
 [8 8 8 2]]


In [113]:
a.sum()

48

In [27]:
a.min(axis=0)

array([1, 4, 4, 0], dtype=int32)

In [28]:
a.max(axis=1)

array([6, 7, 8], dtype=int32)

![](https://quera.org/qbox/view/sfVrSgbDvL/sum.gif)

---

In [116]:
heights = np.array([[194, 185, 183, 184, 178, 178, 190, 187, 187, 179, 186], 
                    [192, 173, 194, 184, 170, 189, 170, 170, 176, 173, 185]])
print('Iran vs Spain')
print('Mean height:', heights.mean(axis=1))
print('Standard deviation:', heights.std(axis=1))

Iran vs Spain
Mean height: [184.63636364 179.63636364]
Standard deviation: [4.79152144 8.91650897]


In [117]:
print('Min:', np.min(heights, axis=1)) 
print('25th percentile:', np.percentile(heights, 25, axis=1)) 
print('Median:', np.median(heights, axis=1))
print('75th percentile:', np.percentile(heights, 75, axis=1))
print('Max:', np.max(heights, axis=1))

Min: [178 170]
25th percentile: [181.  171.5]
Median: [185. 176.]
75th percentile: [187. 187.]
Max: [194 194]


---

In [118]:
b = np.array([8,3,5,9,2,6,4])
np.argmax(b)

3

---

In [119]:
np.argmin(b)

4

---

In [120]:
b = np.array([1,2,3])
np.product(b)
np.prod(b)

6

---

In [121]:
np.var(b)

0.6666666666666666

---

# __**Broadcasting**__

![](https://quera.org/qbox/view/bwy2GQBjAt/ufunc.gif)

In [3]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 2, 2, 2])
a * b

array([0, 2, 4, 6])

In [4]:
2 * a

array([0, 2, 4, 6])

In [8]:
a = np.arange(12).reshape(3, 4)

b = np.array([3, 2, 1, 0])

In [6]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
print(b)

[3 2 1 0]


In [9]:
a + b

array([[ 3,  3,  3,  3],
       [ 7,  7,  7,  7],
       [11, 11, 11, 11]])

![](https://quera.org/qbox/view/2NggXfAdmV/ufunc2.gif)

In [11]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
b = np.array([8, 4, 0]).reshape(3, 1)
print(b)
a + b

[[8]
 [4]
 [0]]


array([[ 8,  9, 10, 11],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

In [25]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4]).reshape(4, 1)
print(a)
print(b)

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]]


In [26]:
c = a * b
c

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20]])

---

In [36]:
col_mean = c.mean(axis=0)
print(col_mean)

[ 2.5  5.   7.5 10.  12.5]


In [37]:
a = np.random.normal(5, 1, (4, 5))
print(a)

[[4.40306179 4.56910641 6.24986798 5.00984535 6.63252508]
 [4.35167196 5.60282677 5.07239742 2.70779866 4.48776942]
 [5.28810281 4.31432795 4.56840515 4.78914471 5.23676748]
 [3.85889967 5.9405604  5.56327184 4.7271884  4.85223132]]


In [38]:
col_mean = a.mean(axis=0)
print(col_mean)

[4.47543406 5.10670538 5.3634856  4.30849428 5.30232333]


In [40]:
a -= col_mean
print(a)

[[-0.07237227 -0.53759897  0.88638239  0.70135107  1.33020176]
 [-0.1237621   0.49612139 -0.29108818 -1.60069562 -0.8145539 ]
 [ 0.81266875 -0.79237744 -0.79508044  0.48065043 -0.06555584]
 [-0.61653438  0.83385501  0.19978624  0.41869412 -0.45009201]]


---

# __**Comparison and Boolean logic**__

In [42]:
a = np.array([2, 13, -5, -3, 19, -17])
a < 7 # سمت راست مقایسه به شکل یک آرایه (,6) با مقادیر 7 در می‌آید

array([ True, False,  True,  True, False,  True])

In [43]:
a == np.sqrt(a ** 2)  # دو سمت مقایسه می‌توانند هم‌نوع نباشند اما مقایسه‌پذیر باشند

array([ True,  True, False, False,  True, False])

In [44]:
t = np.array([[10, 12, 11, 17, 15, 11, 14],
             [13, 15, 18, 21, 19, 18, 17],
             [18, 20, 21, 19, 23, 24, 22],
             [20, 23, 19, 21, 25, 22, 21]])

In [45]:
t > 20 # خروجی یک آرایه (7 ,4) با مقادیر بولی است

array([[False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False],
       [False, False,  True, False,  True,  True,  True],
       [False,  True, False,  True,  True,  True,  True]])

In [46]:
np.count_nonzero(t > 20)

10

In [64]:
t

array([[10, 12, 11, 17, 15, 11, 14],
       [13, 15, 18, 21, 19, 18, 17],
       [18, 20, 21, 19, 23, 24, 22],
       [20, 23, 19, 21, 25, 22, 21]])

In [63]:
np.sum(t > 20, axis=0)

array([0, 1, 1, 2, 2, 2, 2])

In [62]:
np.sum(t > 20, axis=1)

array([0, 1, 4, 5])

In [65]:
np.any(t > 30)

False

In [66]:
np.all(t >= 10)

True

In [67]:
t

array([[10, 12, 11, 17, 15, 11, 14],
       [13, 15, 18, 21, 19, 18, 17],
       [18, 20, 21, 19, 23, 24, 22],
       [20, 23, 19, 21, 25, 22, 21]])

In [68]:
np.sum((t >= 15) & (t <= 20))

12

In [69]:
np.sum(~((t < 15) | (t > 20)))

12

----

# __**Boolean Indexing**__

![](https://quera.org/qbox/view/SdznWWm8jE/boolean%20indexing.gif)

In [70]:
t = np.array([[10, 12, 11, 17, 15, 11, 14],
              [13, 15, 18, 21, 19, 18, 17],
              [18, 20, 21, 19, 23, 24, 22],
              [20, 23, 19, 21, 25, 22, 21]])

In [71]:
t[(t >= 15) & (t <= 20)]

array([17, 15, 15, 18, 19, 18, 17, 18, 20, 19, 20, 19])

In [72]:
print('میانگین دمای هوا در روزهای گرم‌تر از ۲۰ درجه:', t[t > 20].mean())
print('میانه دمای هوا در روزهای سردتر از ۲۰ و گرم‌تر از ۱۵ درجه:', np.median(t[(t > 15) & (t < 20)]))

میانگین دمای هوا در روزهای گرم‌تر از ۲۰ درجه: 22.3
میانه دمای هوا در روزهای سردتر از ۲۰ و گرم‌تر از ۱۵ درجه: 18.0


In [75]:
calendar = np.arange(4*7).reshape(4, 7)
calendar

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [ ]:
holidays = (calendar%7 >= 5) # آرایه بولی متناظر روزهای آخر هفته (پنج‌شنبه و جمعه)
first_mid = (calendar < 2*7) # آرایه بولی متناظر روزهای دو هفته اول اردیبهشت
print('میانه دمای روزهای آخرِ هفته کل ماه:', np.median(t[holidays]))
print('میانه دمای دو هفته نخست ماه:', np.median(t[first_mid]))
print('میانگین دمای روزهای آخرِ هفته در دو هفته پایانی ماه:', np.mean(t[~first_mid & holidays]))

---

**Fancy Indexing**

![](https://quera.org/qbox/view/Wc4NcDdn8s/fancy%20indexing.gif)

In [76]:
a = np.array([1, 2, 4, 8, 16, 32])
ind = [2, 3, 5]
a[ind]

array([ 4,  8, 32])

In [77]:
ind = np.array([[2, 3],
               [4, 1]])
a[ind]

array([[ 4,  8],
       [16,  2]])

In [78]:
a = np.arange(12).reshape(4, 3)
print(a)
row = np.array([0, 2, 3, 2])
col = np.array([0, 2, 1, 0])
a[row, col]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([ 0,  8, 10,  6])

In [80]:
row[:, np.newaxis]

array([[0],
       [2],
       [3],
       [2]])

In [81]:
[row[:, np.newaxis], col]

[array([[0],
        [2],
        [3],
        [2]]),
 array([0, 2, 1, 0])]

In [82]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
a[row[:, np.newaxis], col]

array([[ 0,  2,  1,  0],
       [ 6,  8,  7,  6],
       [ 9, 11, 10,  9],
       [ 6,  8,  7,  6]])

---

In [83]:
a = np.array([2, 1, 3, 4, 5])
a[a%2 == 0] *= 10
print(a)

[20  1  3 40  5]


In [86]:
a = np.array([2, 1, 3, 4, 5])
np.add.at(a, [0, 0, 0, 1, 1, 2], 5)
print(a)

[17 11  8  4  5]


---

# __*Sorting and linear algebra*__

### *Insertion_sort*

- O(n^2)
- not great in efficency for great values and big data

In [87]:
def insertion_sort(a):
    for i in range(len(a)):
        j = i
        while j > 0 and a[j] < a[j-1]:
            a[j], a[j-1] = a[j-1], a[j]
            j -= 1         

In [88]:
a = np.array([7, 3, 11, 13, 5])
insertion_sort(a)
print(a)

[ 3  5  7 11 13]


---

In [90]:
a = np.array([5, 2, 9, 4, 1])
np.sort(a)

array([1, 2, 4, 5, 9])

In [91]:
a.sort()
print(a)

[1 2 4 5 9]


In [92]:
a = np.random.randint(0, 10, (4, 5))
print(a)

[[2 0 5 2 8]
 [9 8 5 7 0]
 [5 2 1 8 1]
 [8 8 1 4 6]]


In [93]:
np.sort(a, axis=0) #ستونی

array([[2, 0, 1, 2, 0],
       [5, 2, 1, 4, 1],
       [8, 8, 5, 7, 6],
       [9, 8, 5, 8, 8]])

In [95]:
np.sort(a, axis=1) #سطری

array([[0, 2, 2, 5, 8],
       [0, 5, 7, 8, 9],
       [1, 1, 2, 5, 8],
       [1, 4, 6, 8, 8]])

---

## *np.partition??*

In [103]:
a = np.array([20,50,90,10,60])
p = np.partition(a, 0)
p

array([10, 50, 90, 20, 60])

In [104]:
a = np.array([20,50,90,10,60])
p = np.partition(a, 1)
p

array([10, 20, 90, 50, 60])

In [105]:
a = np.array([20,50,90,10,60])
p = np.partition(a, 2)
p

array([10, 20, 50, 90, 60])

In [106]:
a = np.array([20,50,90,10,60])
p = np.partition(a, 3)
p

array([10, 20, 50, 60, 90])

In [107]:
a = np.array([20,50,90,10,60])
p = np.partition(a, 4)
p

array([10, 20, 50, 60, 90])

---

In [108]:
a = np.random.randint(0, 10, (4, 5))
a

array([[2, 1, 4, 6, 0],
       [6, 6, 7, 9, 4],
       [1, 0, 8, 2, 3],
       [8, 6, 5, 0, 8]])

In [111]:
np.partition(a, 2, axis=1)

array([[0, 1, 2, 6, 4],
       [4, 6, 6, 9, 7],
       [0, 1, 2, 8, 3],
       [0, 5, 6, 8, 8]])

In [112]:
a = np.array([5, 2, 7, 3, 1])
ind = np.argsort(a)
print(ind)

[4 1 3 0 2]


---

In [113]:
def my_sort(a): #بازگشتی
    if len(a) == 1:
        return
    mid = len(a)//2
    a.partition(mid)
    my_sort(a[:mid])
    my_sort(a[mid:]) 

In [114]:
a = np.array([3, 5, 1, 4, 2])
my_sort(a)
print(a)

[1 2 3 4 5]


---

In [115]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print('x =', x)
print('y =', y)

x = [1 2 3]
y = [4 5 6]


In [116]:
np.matmul(x, y)

32

In [117]:
np.dot(x,y)

32

---

In [123]:
a = np.random.randint(1, 10, (3, 2))
b = np.random.randint(1, 10, (2, 3))
print(a)
print("------------------")
print(b)

[[3 9]
 [3 9]
 [7 9]]
------------------
[[7 7 3]
 [2 2 5]]


In [124]:
np.matmul(a, b)

array([[39, 39, 54],
       [39, 39, 54],
       [67, 67, 66]])

---

In [125]:
print(x)
print("-------------------------------------")
print(y)

[1 2 3]
-------------------------------------
[4 5 6]


In [126]:
print(x @ y)

32


In [127]:
print(a.dot(b))

[[39 39 54]
 [39 39 54]
 [67 67 66]]


----------

In [128]:
from numpy.linalg import inv, det
a = np.random.randn(4, 4)
print(a)

[[-1.26805549 -0.12619352  0.47150789  1.767994  ]
 [ 0.74527264  1.86826341  0.91933832  1.45928984]
 [ 1.3615265  -0.38907672 -0.02564636 -1.69148767]
 [-0.83392843 -0.14520586 -1.16171112  1.38222153]]


In [129]:
det(a)

-3.6284348743009827

In [130]:
inv(a)

array([[ 0.65125397,  0.38980097,  1.4587583 ,  0.54059783],
       [-1.17505098,  0.14325453, -1.37685511, -0.3331595 ],
       [ 0.61361081,  0.03574517,  0.19195523, -0.58770093],
       [ 0.78519498,  0.28026844,  0.89679483,  0.52068678]])